### ISSUE TITLE
Meta-Registry : Impl event sourcing information (Tokenized CC, Offseting CC, etc...) recovery

### ISSUE THREAD

**Issue by Khyati729** [Carbonable/meta-registry-backend#1]
**Description**
---
A clear and concise description of the Feature

**Acceptance Criteria**
---

- [ ] Add and describe Acceptance Criteria
- [ ] Add and describe Acceptance Criteria

**Additional context**
---
From Ticket: Carbon Registry (Carbonable) in Web2 based on event #280

**Comment by MartianGreed** [comment]
keep track of each cc his whole lifetime history

**Comment by MartianGreed** [comment]
Prerequisites : 
- setup project with some cc and some retired (planned on 22.04 with Arn0d)
- define what we want to build (for now basic tool to keep track on what's happening onchain with cc's)
